### ISSUE TITLE
[Enhancement] Approve if other status check has passed

### ISSUE THREAD

**Issue by cswendrowski** [palantir/policy-bot#102]
Github status check enforcement is an "all must pass" system. This poses a problem for our workflow since we only trigger builds if that portion of the code has changed - we would prefer to use a "one or the other" style system as a minimum, and preferably a "if this code section changed, require this build" setup down the line

I would like to setup an approval like so:

```yaml
policy:
  approval:
    - and:
      - code has changed
      - or:
        - the API build has passed
        - the Client build has passed
      - the deploy has passed

approval_rules:
    - name: the API build has passed
      if:
        status_check_passed: My.Company.Project.API - CI
```

policy-bot already has read access for Status checks, but it does not appear to be currently possible to setup the above approval step.

**Comment by bluekeyes** [comment]
If I understand the request correctly, this is a use we hadn't even thought of: using Policy Bot to aggregate other status checks that may or may not be present into a single check that can be required. I like the idea!

In your case, it looks like the rules would likely be auto-approved, but I could also see this being useful for changing approval conditions: requiring extra review if a certain optional status passed or failed.

From an implementation perspective, it should be relatively straightforward:

1. Add methods for reading successful and failed statuses to `pull.Context`
2. Define the new predicates
3. Update the `status` event handler (and add a new handler for either `check_suite` or `check_run`) to re-evaluate the policy on status changes. To avoid too many requests, make sure to filter by check status and possibly the content of the policy before evaluating everything else.

**Comment by cswendrowski** [comment]
For bot-opened PR's (we have a bot that automatically updates dependencies for us), we currently use bulldozer to automatically close the PR once someone has reviewed it. We would love for policy-bot to automatically approve those PR's once one of the two builds succeeds. We would still tie an approval to any user-edited PR's
```yaml
policy:
  approval:
    - and:
      - code has changed
      - or:
        - the API build has passed
        - the Client build has passed
      - the deploy has passed
      - or:
        - the PR was opened by a bot
        - the owning team has approved
```

That implementation seems sound from what I understand of your codebase. This one seems a bit outside of what I can accomplish myself having never written Go before, but I'll play around with Go this weekend and see if it's easier than I'm expecting
