### ISSUE TITLE
Policy Bot 404 on webhook post

### ISSUE THREAD

**Issue by cswendrowski** [palantir/policy-bot#103]
I am connecting to a private Enterprise org deployed to the same internal network as the policy-bot docker image.

I have my settings setup as so:
```yaml
github:
  # The URL of the GitHub homepage
  web_url: "https://github.<company>.com"
  # The base URL for v3 (REST) API requests
  v3_api_url: "https://github.<company>.com/api/v3"
  # The base URL for v4 (GraphQL) API requests
  v4_api_url: "https://github.<company>.com/api/graphql"
```

I have verified I can hit these endpoints myself via a REST client.

When a webhook comes in, the container is dropping a 404 error `
{"level":"info","rid":"bkmf1qr11808ga9im6jg","method":"POST","path":"/","status":404,"size":19,"elapsed":0.06792,"time":"2019-07-15T21:32:27.549643814Z","message":"http_request"}`

I'm not sure what method is generating the 404 unfortunately, making this error hard to debug on my end
