### ISSUE TITLE
[Enhancement] Support Not

### ISSUE THREAD

**Issue by cswendrowski** [palantir/policy-bot#108]
We structure our projects so that all code is in a `src/` folder, and currently have a policy that looks like the following:
```yaml
- name: no code changed
    if:
      only_changed_files:
        paths:
          - "README"
          - "gitignore"
          - "gitattributes"
          - "github/.*"
```

It would be convenient if we didn't have to maintain this list and instead could approve if files in a folder didn't change.

Looking through the code, it appears that `Predicate`s do not support nesting. Two options seem to be available:

1) Add a new YAML section in `Rule` for nots. The rules would be loaded and predicates evaluated as normal, except the predicate would be inversed ([see here](https://github.com/palantir/policy-bot/blob/93cf299ba0824e4164ba0396f99227ef6ad419af/policy/approval/approve.go#L76)). Predicates are currently "and" for group logic which seems fine so long as it's documented
```yaml
- name: no code changed
    not:
      changed_files:
        paths:
          - "src/.*"
```

2) Add new Policy group options of `nor` and `nand` ([see here](https://github.com/palantir/policy-bot/blob/93cf299ba0824e4164ba0396f99227ef6ad419af/policy/approval/parse.go#L96)). The rules would be evaluated and inversed. 
```yaml
policy:
  approval:
    - or:
      - the owner team has approved
      - nor:
      	- code changed
```
