### ISSUE TITLE
 Allow writing policies which mention repo 'admins' or 'collaborators'

### ISSUE THREAD

**Issue by jmcampanini** [palantir/policy-bot#15]
I want to make sure certain excavator changes can merge without human intervention in _every single repo_ in foundry.  The problem is that I need to generate a policy.yml that is appropriate for each repo, taking into account all their different collaborators and admins.  

## Proposal

Allow the values 'admins' and 'collaborators' in policy.yml files, e.g.:

```yml
policy:
  approval:
    - or:
      - maintainer approval
      - excavator only touched gradle files

approval_rules:

  - name: maintainer approval
    requires:
      count: 1
      github:
        - admins # <--- policy-bot would expand this to all users & teams with admin access
        - collaborators

  - name: excavator only touched gradle files
    requires:
      count: 0
    if:
      has_author_in:
        users: [ "svc-excavator" ]
      only_changed_files:
        paths:
          - "^.*gradle$"
```

This ensures there's one source of truth for who is in control of a repository and for the moment it's the github settings tab.
