### ISSUE TITLE
unsupported protocol scheme error when not setting up github urls

### ISSUE THREAD

**Issue by huydinhle** [palantir/policy-bot#150]
When I deployed my policy-bot, I kept getting this error 
```yaml
could not get access_tokens from GitHub API for installation ID 123456: unsupported protocol scheme
```
Turns out it's because I forgot to set 
```yaml
    github:
      web_url: "https://github.com"
      v3_api_url: "https://api.github.com"
      v4_api_url: "https://api.github.com/graphql"
```

This was very hard for me to debug because the error message isn't very useful. Can we have sane default for all the github urls if people don't set them?
