### ISSUE TITLE
request_review workflow: assigning based on status checks?

### ISSUE THREAD

**Issue by iamdanfox** [palantir/policy-bot#160]
## What happened

We've been using the request_reviews functionality to try to ensure incoming PRs (across >100 repos) get attention from a team member by pushing them into team members' review requested inbox, but recently I've discovered some excavator PRs are stuck with nobody assigned.

The policy includes this clause

```yml
  - name: infrastructure-notify has been notified
    options:
      allow_contributor: false
      request_review:
        enabled: true
    requires:
      count: 1
      teams: [ "palantir/infrastructure-notify" ]
``` 

But @asvoboda explained that policy-bot doesn't actually notify us because another clause has already approved:

```yml
  - name: excavator only touched baseline, circle, gradle files, godel files, docker-compose-rule config or versions.props
    requires:
      count: 0
    if:
      has_author_in:
        users: [ "svc-excavator-bot" ]
      only_changed_files:
          - "changelog/@unreleased/.*\\.yml"
          - "^\\.baseline/.*$"
          - "^\\.circleci/.*$"
          - "^\\.docker-compose-rule\\.yml$"
          - "^.*gradle$"
          - "^gradle/wrapper/.*"
          - "^gradlew$"
          - "^gradlew.bat$"
          - "^gradle.properties$"
          - "^settings.gradle$"
          - "^godelw$"
          - "^godel/config/godel.properties$"
          - "^versions.props$"
          - "^versions.lock$"
```

This means we can't quite rely on policy-bot partitioning up PRs in need of attention, and would need to do a mixture of proactively checking all these repos and relying on our inboxes.

## What did you want to happen?

Simplest option:
- policy-bot _always_ request reviews, even if another condition is already green. This would result in some superfluous email notifications for excavators that would auto-mrege, but would ensure our [review-requested](https://github.com/pulls/review-requested) dashboards should be complete. I worry this might desensitise people to the email notifications when someone 'requests a reviews'.

More complicated:
- policy-bot could understand required status checks somehow, and make sure PRs with failing CI get assigned a reviewer even if they were otherwise approved. (0-approval PRs that pass CI wouldn't need to notify anyone)
