### ISSUE TITLE
request_review expect a team to be a contributor

### ISSUE THREAD

**Issue by NargiT** [palantir/policy-bot#165]
Hello,

I face an issue with `request_review` feature. At least I consider it buggy.

I have a team of team (let's call it MegaTeam) in github organization and my repository has read only for MegaTeam. The RequestorTeam is part of MegaTeam and I configured policy bot with the following.

*Given*:
```
policy:
  approval:
    - policy

approval_rules:
  - name: policy
    options:
      request_review:
      enabled: true
      mode: all-users
    requires:
      count: 2
      teams: ["myorg/requestorteam"]
      admins: false
      write_collaborators: false
```
*When* pull request is created by anyone
*Then* 0 users are assigned to the pull request
*When* `requestorteam` is added as read collaborator
*And* Pull request is created
*Then* all member of the *requestorteam* are assigned

I expect policy to be able to "see" that requestorteam is part of collaborator, instead to explicitly add them.
