### ISSUE TITLE
Allow for approval from users in different teams

### ISSUE THREAD

**Issue by styu** [palantir/policy-bot#169]
I have a frontend monorepo whose packages are divided amongst several teams. There is one file in each package that is touched frequently, package.json. I would like to configure policy bot such that if package.json files of a single team is touched, it only needs approval from that team. If package.json files belonging to multiple teams are touched, you only need approval from 2 people from 2 different teams (rather than hunting for approval from every team). My proposal for how to configure it would be something like:

```
  - name: +2 approval from teams for package.json
    options:
      allow_contributor: false
    requires:
      count: 2
      unique_teams:
        - team1
        - team2
        - team3
    if:
      changed_files:
        paths:
          - "^packages/.*/package\\.json$"
```

The above would say that you require 2 approvals from 2 different users from any of the specified teams in `unique_teams` to satisfy the rule
