### ISSUE TITLE
Is it possible to run another status check as part of an approval policy?

### ISSUE THREAD

**Issue by Koshak118** [palantir/policy-bot#182]
Hi,
Thanks for sharing this bot, first of all

We've got a plenty of other status checks running on our repo, e.g Sonar Bot. So Is it possible to run some specific status check, that Sonar Bot, for example, as a part of an approval policy?

I've seen #102 issue which refers this functionality, it is closed now but I am not sure what is the status of it nowadays.

**Comment by bluekeyes** [comment]
You can use the `has_successful_status` predicate to make an approval rule conditional on some other status check passing. For example:

```yaml
approval_rules:
  - name: auto-approved if sonar passes
    if:
      has_successful_status: ["sonar-bot"]
    requires:
      count: 0
```

If a pull request has a passing `sonar-bot` status, then that rule applies and is automatically approved.

I'm not sure if this is the functionality you are looking for, but it is the only integration with status checks that we currently support.
