### ISSUE TITLE
Policy-bot emitting metrics

### ISSUE THREAD

**Issue by xiaotianq** [palantir/policy-bot#209]
Hi, there
    How can we configure policy-bot or it's yaml file to emit metrics to certain port?

**Comment by bluekeyes** [comment]
Currently, policy-bot can emit metrics to a Datadog agent (or any service that understands the [DogStatsD protocol](https://docs.datadoghq.com/developers/dogstatsd/).) Add the following to your server configuration to enable it:

```yaml
datadog:
  # the address of the agent or receiving service (required)
  address: 127.0.0.1:8125

  # the reporting interval (optional, default is 10s)
  # interval: 10s
 
  # additional tags to attach to metrics (optional, default is an empty list)
  # tags: []
```

Unfortunately, we don't support any other metric output at this time.

**Comment by xiaotianq** [comment]
Thanks for the information

**Comment by xiaotianq** [comment]
Had one container running policy-bot, another running the agent.
Both are on the default network bridge.
Looks like the agent not receiving anything from policy-bot

```
sudo: unable to resolve host policy-bot-0a6a1538fc2666b12
CONTAINER ID        IMAGE                                    COMMAND                  CREATED             STATUS                 PORTS                                        NAMES
9ae0245483f9        prom/statsd-exporter:v0.10.5             "/bin/statsd_exporter"   2 hours ago         Up 2 hours (healthy)   0.0.0.0:9102->9102/tcp, 9125/tcp, 9125/udp   docker_statsd-exporter
fd3a42be773b        palantirtechnologies/policy-bot:1.17.0   "bin/linux-amd64/pol…"   2 hours ago         Up 2 hours             0.0.0.0:8080->8080/tcp                       docker_policy-bot
```

**Comment by xiaotianq** [comment]
The config on policy-bot side:
```
datadog:
  address: 127.0.0.1:9125
```

When curl the :9102 port on agent, [logs](https://gist.github.com/xiaotianq/b5a3adc0784b292fd6f3b6f3db51147f)



Anything missing from configs or other setting?

**Comment by bluekeyes** [comment]
Unless you are using [host networking](https://docs.docker.com/network/host/), referencing `127.0.0.1` from _inside_ a container usually resolves to the container itself, not the host it is running on. To fix this, you can either:

1. Set `datadog.address` to the IP or the hostname of the host that is running the Docker containers. If you take this approach, you will have to expose port 9125 to the host.
2. Set `datadog.address` to the container/service name of the exporter. If you're using `docker-compose`, that's probably something like `statsd-exporter:9125`.

**Comment by xiaotianq** [comment]
Using method 2 or host networking still not getting the metrics out. 

Command we run using host networking.

Policy-bot
`/usr/bin/docker run --rm --name %N --publish 8080:8080 --network host --volume /opt/policy-bot/config:/secrets palantirtechnologies/policy-bot:1.17.0`

Statsd-exporter
`/usr/bin/docker run --rm --name %N --publish 9102:9102/tcp --network host prom/statsd-exporter:v0.10.5`

**Comment by xiaotianq** [comment]
We use saltstack to luanch status:

```
docker:
  containers:
    policy-bot:
      image: palantirtechnologies/policy-bot:1.17.0
      container_args: []
      extra_args:
        - '--publish 8080:8080'
        - '--network host'
        - '--volume /opt/policy-bot/config:/secrets'
    statsd-exporter:
      image: prom/statsd-exporter:v0.10.5
      container_args: []
      extra_args:
        - '--publish 9102:9102/tcp'
        - '--network host'
```

Not sure if the 1st method work. 
So in the configs, `127.0.0.1` means the ip address of the host?

**Comment by bluekeyes** [comment]
Yeah, if you are running Docker on a host with IP 10.10.10.10 or hostname `docker-host.domain`, you would want the config to look like:

```
datadog:
  address: 10.10.10.10:9125
```

or

```
datadog:
  address: docker-host.domain:9125
```

Note that in both cases, you'll need to publish UDP port 9125 from the `statsd-exporter` container.

**Comment by xiaotianq** [comment]
> or

Should I publish 9125 or just expose this port?

If publish, should I publish to 127.0.0.1 or all interface?

**Comment by bluekeyes** [comment]
I believe you should add `--publish 9125:9125/udp` to your Docker invocation:

```
    statsd-exporter:
      image: prom/statsd-exporter:v0.10.5
      container_args: []
      extra_args:
        - '--publish 9102:9102/tcp'
        - '--publish 9125:9125/udp'
        - '--network host'
```
