### ISSUE TITLE
And/OR Rules are not working properly

### ISSUE THREAD

**Issue by KnisterPeter** [palantir/policy-bot#222]
We are using policy-bot to do reviews.
There are a few PRs (e.g. created by renovate) which should not need reviews for certain conditions.
From the screenshot you can see that this looks correct:

![Bildschirmfoto von 2020-08-21 11-37-42](https://user-images.githubusercontent.com/327445/90876338-cbb40080-e3a2-11ea-8336-79d32ddf5bf5.png)

These are the rules we have here:

```yaml
#
# To validate file run:
# curl https://policy-bot.xing.io/api/validate -XPUT -T .github/policy-bot.yml
#
policy:
  approval:
    - or:
        - is renovate PR
        - and:
            - approved by solar
            - approved by web platform
            - approved by supi
            - approved by disco
            - approved by documentation

approval_rules:
  - name: is renovate PR
    if:
      has_author_in:
        users: ['renovate-bot']
      only_changed_files:
        paths:
          - 'package.json'
          - '^yarn.lock'
          - '^core/eslint/index.js'
          - '^patches/.*'
    requires:
      count: 0

  - name: approved by solar
    if:
      changed_files:
        paths:
          - '^.github/.*'
...
```

But the status check on the PR is still pending even though the policy-bot site declares it as approved:

![Bildschirmfoto von 2020-08-21 11-39-49](https://user-images.githubusercontent.com/327445/90876512-103f9c00-e3a3-11ea-95ff-13a08719b718.png)
