### ISSUE TITLE
Regression since 1.17.0 - policy does not recognize my github app name

### ISSUE THREAD

**Issue by NargiT** [palantir/policy-bot#230]
Hello,

We are using GitHub Enterprise Server 2.20.5 so I cannot do any test on +1.17.1.

I did an upgrade from 1.16.3 to 1.17.0 and to 1.17.1 and now policy is not able to recognize the bot user and fail the status check.

Some context:
I use a Github App to create pull request to update my repository (same idea as renovate or dependabot).
The commit and the author have the following format:

```
Author:     mybot[bot] <mybot[bot]@users.noreply.github.domain.ch>
AuthorDate: Tue Sep 8 06:39:34 2020 +0000
Commit:     mybot[bot] <mybot[bot]@users.noreply.github.domain.ch>
CommitDate: Tue Sep 8 06:39:34 2020 +0000
```

```
policy:
  approval:
    - mybot upgrade

approval_rules:
  - name: mybot upgrade
    if:
      has_author_in:
        users: ['mybot[bot]']
      author_is_only_contributor: true
      targets_branch:
        pattern: ^master
    options:
      invalidate_on_push: true
```
The error

```
The pull request author "mybot" does not meet the required membership conditions
```

And if I modify the users list to `['mybot']` only I get another error

```
Commit 8a82a72953 was authored or committed by a different user
```

I also tried to remove the "bot" and only use mybot for commit and pull request creation, but end up with the previous error `Commit xxxx was authored or committed by a different user`

This is working very well with 1.16.3 but since 1.17.0 policy does not recognize my bot anymore.
Which field is used to match the user name ?

Looks like the issue comes from this changes https://github.com/palantir/policy-bot/compare/v1.16.3...v1.17.0
