### ISSUE TITLE
support predicate for source branch

### ISSUE THREAD

**Issue by danny-wh** [palantir/policy-bot#241]
It seems like it would be useful to have an analogous version of `targets_branch` for specifying the source branch. For my particular use case, I would like to have a policy where pull requests to the `master` branch can only come from the `develop` branch.

**Comment by bluekeyes** [comment]
While this would be relatively easy to add, I'm not sure it would solve your problem given how Policy Bot currently handles rules and predicates. When a predicate is not true, the rule is marked as skipped and does not contribute to `and` and `or` conditions. This means you can use a `source_branch` predicate to add additional rules for some branches (for instance, automatically approving pull requests from `develop` to `master`) but couldn't use it to block pull requests that don't meet the conditions (except maybe through a hack like requiring an impossible approval condition.)

Do you have an example policy you'd like to update with this new predicate?

**Comment by danny-wh** [comment]
Yeah, that's a fair point. I think I might still find this useful, even if I just require approval instead of outright blocking merges from other branches. I'm thinking the overall policy would look something like this, making merges from develop to master free:

```yaml
policy:
  approval:
  - or:
    - any two team members have approved # allows for two contributors to both approve and pass the check
    - a non-contributing team member has approved
    - merge from develop to master

  disapproval:
    requires:
      teams: ["org/team"]

approval_rules:
- name: any two team members have approved
  options:
    invalidate_on_push: true
    allow_contributor: true
  requires:
    count: 2
    teams: ["org/team"]

- name: a non-contributing team member has approved
  options:
    invalidate_on_push: true
  requires:
    count: 1
    teams: ["org/team"]

- name: merge from develop to master
  if:
    targets_branch: master
    source_branch: develop
```

I could use an impossible condition (maybe a very large number of required reviews) as a hack like you mentioned, but I think just requiring a review still is good enough.
