### ISSUE TITLE
Add an optional description to rules

### ISSUE THREAD

**Issue by robbiemcmichael** [palantir/policy-bot#250]
Some more complicated rules might require a few sentences to describe to users what sort of approvals are required to satisfy the rule. It is possible to use a complicated rule name to describe this, but it's not nice for two reasons
1. The name gets repeated in the `.policy.approval` list. When the long name gets updated because someone wants to reword the approval requirements, they need to remember to make the same change to this list.
2. The UI looks strange with a long name as the large, bold text suggests it was probably designed around the assumption that the name would be short.

### Proposal

Add an optional `description` field to rules which can be used to store the detailed information for users about what is required to get the approval rule to pass. Since this field is optional, the change would be backwards compatible and have no effect for existing configurations of policy-bot.

As an example, consider the following config file:

```yaml
policy:
  approval:
  - Team 1
  - Team 2
  - Admin

approval_rules:
- name: Team 1
  description: Changes to config must be approved by your own team
  requires:
    count: 1
    teams:
    - myorg/team1
  if:
    changed_files:
      paths:
      - '^teams/team1/.*'
- name: Team 2
  description: Changes to config must be approved by your own team
  requires:
    count: 1
    teams:
    - myorg/team2
  if:
    changed_files:
      paths:
      - '^teams/team2/.*'
- name: Admin
  description: All other changes must be approved by an admin
  requires:
    count: 1
    teams:
    - myorg/admin
  if:
    changed_files:
      paths:
      - '.*'
      ignore:
      - '^teams/.*'
```

Which could look something like this:

![image](https://user-images.githubusercontent.com/2044464/100578376-21dafd00-331d-11eb-8228-a962a816b877.png)
