### ISSUE TITLE
Use targets_branch in disapproval rules similarly as approval rule predicate

### ISSUE THREAD

**Issue by ghost** [palantir/policy-bot#272]
```yml
policy:
  approval:
    - and:
        - approvalrule1
  disapproval:
    if:
      targets_branch:
        pattern: "^(develop|production)$"
      changed_files:
        paths:
          - "^ScriptFolder/"
          - ".github/"
    requires:
      teams: ["adminteam"]
      
# the list of rules
approval_rules:
  - name: approvalrule1
    if:
      targets_branch:
        pattern: "^(develop|production)$"
      changed_files:
        paths:
          - "^app/"
          - "*.kt"
    options:
      allow_contributor: true
      invalidate_on_push: true
      request_review:
        enabled: true
        mode: teams
    requires:
      count: 1
      teams: ["adminteam"]
 ...
```

Above you can see a part of the rules that we have setup in the policy.yml file.

The issue that I am experiencing is that within the disapproval rule I want to disapprove only if the listed files are part of the changes and that should apply only for the two branches specified and not for the rest that we got. 
Currently any file changes towards the two branched are marked with status disapproved 
```
Status: Disapproved
A precondition of this rule was satisfied
```
