### ISSUE TITLE
add a has_label_in or similar approval rule predicate

### ISSUE THREAD

**Issue by bjlaub** [palantir/policy-bot#29]
I'd like to be able to apply a set of approval rules based on a label, commit message content, or similar marker on a PR that indicates some special set of circumstances that require different approval rules. The use case is something like the following:

- a user wants to merge a PR that would ordinarily be blocked by some failing automated tests or other policy
- they might have the ability to silence or bypass the automated checks in some way
- if they do this, the PR should require special approval from some set of important people who are vouching for the change being OK to submit, even though checks are being explicitly skipped
- to indicate that, the user adds a "Requires-Lead-Approval" label (or similar) to the PR

I'd imagine the configuration looking something like:
```
approval_rules:
  - name: important people have approved a scary change
    if:
      has_label_in:
        label: ["Requires-Lead-Approval"]
    requires:
      count: 1
      teams:
        - "ImportantGatekeepers"
```

Alternative to the label approach might be something where a commit message or the PR description has a special marker, e.g.
```
approval_rules:
  - name: important people have approved a scary change
    if:
      description_has: "==API_BREAK=="
...
```

**Comment by bjlaub** [comment]
thinking about this a bit more, it might be better for my use case this were something like a `commit_message_contains` predicate, e.g.:
```
approval_rules:
  - name: important people have approved a scary change
    if:
      any_commit_message_contains: "==API_BREAK=="
```
would trigger the logic if any commit in the PR matches a regex or something.

Reason for this being that we could also have CI builds that might read content on commit messages use that to determine what checks to run, and then policy-bot and the CI builds will be in sync WRT what's being enforced.

**Comment by zachkirsch** [comment]
+1

Specifically, it'd be great if policy-bot could disapprove all PRs that have the `DO NOT MERGE` label added

**Comment by zachkirsch** [comment]
@bkeyes - does #151 cover the case of disapproving PRs that have the `DO NOT MERGE` label? Or is it just for approving PRs that have certain labels?

**Comment by bluekeyes** [comment]
It only adds the ability for approval rules to be turned on or off based on the existence of labels. I think the ability to change disapproval based on label conditions is a separate feature request, since disapproval doesn't support any predicates at the moment.

**Comment by zachkirsch** [comment]
Would this work?
```yaml
  - name: disapprove all 'DO NOT MERGE' PRs
    if:
      has_labels:
        - DO NOT MERGE
    requires:
      count: 1
      users: []
```
