### ISSUE TITLE
Validation only succeeds if an arbitrary comment exists on the first line of a policy

### ISSUE THREAD

**Issue by artis3n** [palantir/policy-bot#301]
Was debugging an issue with my `.policy.yml` file and realized that the `/api/validate` endpoint will return an error with:

```
{"message":"yaml: mapping values are not allowed in this context","version":"1.21.1"}
```

if the first line of the policy did not include any arbitrary comment, `# ...`.

Any valid policy beginning with:

```yml
policy:
  approval:
```

fails validation, whereas the same policy beginning with:

```yml
# Hello
policy:
  approval:
```

passes validation.

I see we're a few patch versions behind, latest is `1.21.4` and from the API response you can see we are on `1.21.1`, but I don't see anything around this addressed in those versions. Will get our server updated to validate it is still present on the latest version but figured I'd make the issue.

**Comment by bluekeyes** [comment]
Thanks for reporting this. Could you share how you are submitting the policy to the `/api/validate` endpoint? I wasn't able to reproduce this on our instance running 1.21.3, so I'm wondering if something is going wrong with the request rather than with the validation code.

This is what I was using to test:

    curl -T .policy.yml https://policy-bot.domain/api/validate

**Comment by artis3n** [comment]
Oh, definitely. We're running this script as a CI check:

```bash
#!/bin/bash -eux

function validate_policy {
  FILENAME=$1
  curl --silent https://policy-bot.werally.in/api/validate -X PUT -d "@${FILENAME}"
}

for policy in policies/*; do
  printf "\n$policy: "
  validate_policy $policy
done
```

So a real command would look like (with a file `default.yml` in a `policies` directory at the root of the project):

```bash
curl --silent https://policy-bot.werally.in/api/validate -X PUT -d @policies/default.yml
```

**Comment by artis3n** [comment]
Oh, definitely. Use this example policy:

<details>
<summary>example.yml</summary>

```yml
# Validation will only pass if a comment exists on the first line!
policy:
  approval:
    - and:
      - has two approvals
      - approved by codeowner
      - latest commit is reviewed
        
  disapproval:
    if:
      title:
        matches:
          - "(?i).*DNM.*"
          - "(?i).*WIP.*"
          - "(?i).*do not merge.*"
        not_matches:
          - '.*\b[a-zA-Z]+-\d+\b.*'  # something shaped like a jira ticket
      has_labels:
        - "DNM"
        - "WIP"
        - "do not merge"
    options:
      methods:
        disapprove:
          github_review: true
        revoke:
          github_review: true
    requires:
      teams:
        - exampleteam

approval_rules:
  - name: has two approvals
    requires:
      count: 2
      organizations:
        - exampleorg
    options:
      allow_contributor: true
      ignore_update_merges: true
      methods:
        github_review: true

  - name: latest commit is reviewed
    requires:
      count: 1
      organizations:
        - exampleorg
    options:
      invalidate_on_push: true
      ignore_update_merges: true
      methods:
        github_review: true

  - name: approved by codeowner
    options:
      allow_contributor: true
      ignore_update_merges: true
    requires:
      count: 1
      teams:
        - exampleteam
```

</details>

Run with the existing comment, then remove the comment line and run again, you should see:

```bash
➜ curl --silent https://URLHERE/api/validate -X PUT -d @example.yml
{"message":"Policy file is valid","version":"1.21.1"}%

➜ curl --silent https://URLHERE/api/validate -X PUT -d @example.yml
{"message":"yaml: mapping values are not allowed in this context","version":"1.21.1"}%
```
