### ISSUE TITLE
External Services Predicate and API Interface

### ISSUE THREAD

**Issue by IainSteers** [palantir/policy-bot#317]
Policy-bot should have the ability to run what we're calling `external-service-predicates`.

The idea is that we have several internal services, each of which has a view of the compliance/security state of a PR and it would be nice to give policy-bot the ability to interrogate these services, without tying OSS policy-bot to internal Palantir services.

Most likely this would take the form of a new predicate

```go
type ExternalServicePredicate struct {
   Evaluate(ctx context.Context, prctx pull.Context) (bool, string, error)
}
```

Plus an API client and http.Handler interface/spec, with some policy.yml config to define external-services for the repo/policy in question.

Thus allowing any service to implement a "predicate" api endpoint, which receives the encoded pullCtx for evaluation and then returns a json payload indicating the evaluation result (bool and message to match the existing predicates).

Errors (either 5xx/4xx) should be treated by policy-bot as an errored evaluation.

Config will be defined in the policy-bot yaml and will consist of some form of service declaration and then requirement in the approval-rules.

```yaml
external-services:
  some-service:
    url: https://some-service.internal
    
approval_rules:
  - name: product dependencies safe
    requires:
      count: 0
    if:
      only_changed_files:
        paths:
          - "^.*yarn.lock$"
          - "^.*package.json$"
      external_services:
       - some-service
```
