### ISSUE TITLE
Are dependent approvals possible?

### ISSUE THREAD

**Issue by gms8994** [palantir/policy-bot#339]
Is it possible to have rules that are dependent on other rules? For example, I want something like this:

```
---
policy:
  approval:
    - and:
        - the dev team has approved
        - the qa team has approved
        - the uat team has approved

# the list of rules
approval_rules:
  - name: the dev team has approved
    requires:
      count: 2
      teams:
        - "palantir/developers"
    options:
      request_review:
        enabled: true
        mode: random-users
  - name: the qa team has approved
    if:
      has_successful_status: ["the dev team has approved"]
      count: 2
      teams:
        - "palantir/qa"
    options:
      request_review:
        enabled: true
        mode: random-users
  - name: the uat team has approved
    if:
      has_successful_status: ["the qa team has approved"]
      count: 2
      teams:
        - "palantir/uat"
    options:
      request_review:
        enabled: true
        mode: random-users
```

Such that the users in the QA team haven't been requested until the developers have approved the PR, then the UAT members wouldn't be requested until the QA team has approved the PR. But for the overall PR, all approvals have to have been met as normal. Does something like this exist?

**Comment by bluekeyes** [comment]
Sorry, this is not possible at the moment. Policy Bot posts a single status with the result of evaluating the full policy, so you can't make a rule depend on the status from another rule.

You could approximate this if there was overlap between approval methods and supported predicates, but that also doesn't exist right now. For example, if there was a predicate that matched comments, you could require each team to approve using a specific comment that was a predicate for the next rule in the chain. This `has_comment` predicate is not implemented, but if it was, usage would be something like:

```yaml
policy:
  - rule 1
  - rule 2

approval_rules:
  - name: rule 1
    requires:
      count: 1
      teams: ["org/team-1"]
    options:
      methods:
        comments: ["approved by team 1"]
      request_review:
        enabled: true
        mode: random-users
  - name: rule 2
    if:
      has_comment:
        pattern: "approved by team 1"
    requires:
      count: 1
      teams: ["org/team-2"]
    options:
      methods:
        comments: ["approved by team 2"]
      request_review:
        enabled: true
        mode: random-users
```

While not automatic, Policy Bot does support using labels for predicates, so another option might be to ask each reviewing team to also add a label (like `Ready for QA`) after leaving a review that triggers assignment/notification of the next set of reviewers.
