### ISSUE TITLE
feat: ignore edited comments with new option

### ISSUE THREAD

**Issue by devinburnette** [palantir/policy-bot#356]
Firstly, thanks for maintaining such an amazing tool! We hope to get many miles out of it.

Our engineering org has strict governance and compliance rules related to code review / approval. One part of our code review process is ensuring the integrity of an approving PR comment. As a result, edited comments need to be treated with utmost scrutiny. We would love to use github reviews entirely, but still have somewhat of a comment driven PR workflow and there doesn’t seem to be a way to easily determine if an edited approval comment is genuine. In our own tooling, we’ve taken the approach of ignoring edited comments when evaluating approval rules. As we lean into policy-bot, we thought this might be a useful feature in case using the `github_reviews: true` option isn’t sufficient for all use cases. Example policy here:

```yaml
approval_rules:
- name: domain review
  requires:
    count: 1
    teams:
    - "Betterment/engineering"
    permissions:
    - write
  options:
    invalidate_on_push: true
    ignore_edited_comments: true
    methods:
      github_review: false
      comment_patterns:
      - '.*?domain.*?lgtm'
- name: platform review
  requires:
    count: 1
    teams:
    - "Betterment/platform-reviewers"
    permissions:
    - write
   options:
    invalidate_on_push: true
    ignore_edited_comments: true
    methods:
      github_review: false
      comment_patterns:
      -  '.*?platform.*?lgtm'
```

Lastly, I'd be happy to open a pull request if you think this is something worthwhile. Thanks and happy holidays!
