### ISSUE TITLE
feat: add comment matching to github review approval

### ISSUE THREAD

**Issue by devinburnette** [palantir/policy-bot#359]
Hello, it's me again. I have another feature idea that could help us with our use cases.

We love github's built in PR reviews and would love to be able to use policy-bot with github reviews in our PR workflow, but we currently have to rely on comments to distinguish the various types of reviewers that may be members of the same groups. For governance/compliance reasons, we require certain team members to receive multiple reviews for both content and style, whereas for other team members we require only one review based on content.

As you can imagine, it becomes very difficult to delineate which review approval counts for which rule. For example in our org, anyone in engineering can perform a domain review, but a platform expert must perform a platform review. Of course our platform reviewers are also members of engineering, so we need a way to explicitly detect which reviewer is satisfying which rule and so the below example policy didn't work for us.

```yaml
approval_rules:
- name: domain review
  requires:
    count: 1
    teams:
    - "Betterment/engineering"
    permissions:
    - write
  options:
    invalidate_on_push: true
    methods:
      github_review: true
- name: platform review
  requires:
    count: 1
    teams:
    - "Betterment/platform-reviewers"
    permissions:
    - write
   options:
    invalidate_on_push: true
    methods:
      github_review: true
```

I originally thought that some combination of one of the `comments:` options and `github_review: true` would do it, but that doesn't appear to be the case.

We could use comments alone, but there are so many more other features you get with github reviews, like requesting review, integrating codeowners, built in approval dismissal functionality, etc. Leaning into Github Reviews as the canonical source of approval but with the added flexibility of human-enabled opt-in behavior seems like the best fit for us, and we believe this can benefit other teams as well who need to support more nuanced approval rules.

So the feature would be adding comment matching ability for github review body comments in order to determine approval and not just the review approval itself. An example of an accompanying policy file with this change would look like:

```yaml
approval_rules:
- name: domain review
  requires:
    count: 1
    teams:
    - "Betterment/engineering"
    permissions:
    - write
  options:
    invalidate_on_push: true
    methods:
      github_review: true
      github_review_comment_patterns:
      - "domain lgtm"
- name: platform review
  requires:
    count: 1
    teams:
    - "Betterment/platform-reviewers"
    permissions:
    - write
   options:
    invalidate_on_push: true
    methods:
      github_review: true
      github_review_comment_patterns:
      -  "platform lgtm"
```

If you think the above sounds acceptable, I don't think it should be too difficult to implement. As always, I'm happy to take a stab at a PR.
