### ISSUE TITLE
[Question]: Prevent changes to policy

### ISSUE THREAD

**Issue by shresthaujjwal** [palantir/policy-bot#377]
As an enterprise, we would like to use same policy for everyone. In order to do that we would need to centralize the policy.yml configuration, which i can see its possible to do it by pointing the policy to remote repo. But its possible to override that by adding policy.yml in the repo. Is there a way to prevent this, can we add some type of flag or setting that would prevent overriding policy that is defined in one central place?

**Comment by bluekeyes** [comment]
There are two ways I can think of to achieve this, provided people cannot push directly to target branches:

1. Disapprove any PRs that modify the policy file:
   ```yaml
   policy:
     disapproval:
       if:
         changed_files:
           paths: [".policy.yml"] # replace with actual policy path
   ```
   This should post a failed status check on any PR that modifies the policy file. As long as the check is required, this will block PR merges.

2. Require approval conditions for policy changes that can't be (realistically) satisfied:
   ```yaml
   policy:
     approval:
       - policy changes are not allowed

   approval_rules:
     - name: policy changes are not allowed
       if:
         changed_files:
           paths: [".policy.yml"] # replace with actual policy path
       requires:
         count: 999 # some really high count that couldn't happen, or...
         users: ["service-account"] # the name of a user that doesn't exist or a service account for emergencies
   ```

I'd probably try option (1) first, since the red failed status should make it more obvious what is wrong. But option (2) could be valuable, especially if you want to make sure that policy changes require special approval, but could still happen if necessary.

Unfortunately, Policy Bot currently has no option to enforce a single configuration or prevent overrides at the server level, but that might be something we could add.
