### ISSUE TITLE
[Question]: Is it possible to add multiple policy

### ISSUE THREAD

**Issue by shresthaujjwal** [palantir/policy-bot#382]
Is it possible to add multiple policy, i am trying to validate rule like this: If label A than validate policy x, if label B than validate policy y.
To provide more detail each policy x and y will have different rules

**Comment by bluekeyes** [comment]
Policy Bot supports a single policy per repository. However, you can express complex behavior by combining rules using the `and` and `or` operators along with predicates.

Here's an example that might illustrate. If a pull request has "Label A", it needs one approval from "Team A" and an additional approval from the "Compliance" team if it modifies `files/a.yaml`. If a pull request has "Label B", it needs one approval from "Team B" and an additional approval from the "Compliance" team if it modifies `files/b.yaml`. If a pull request is created without one of those labels, Policy Bot will post an error because all rules are skipped.

```yaml
policy:
  approval:
    # rules for policy "A"
    - "A: Approval from Team A"
    - "A: Approval from Compliance"

    # rules for policy "B"
    - "B: Approval from Team B"
    - "B: Approval from Compliance"

approval_rules:
  - name: "A: Approval from Team A"
    if:
      has_labels: ["Label A"]
    requires:
      count: 1
      teams: ["org/team-a"]

  - name: "A: Approval from Compliance"
    if:
      has_labels: ["Label A"]
      changed_files:
        paths: ["files/a\\.yaml"]
    requires:
      count: 1
      teams: ["org/compliance"]

  - name: "B: Approval from Team B"
    if:
      has_labels: ["Label B"]
    requires:
      count: 1
      teams: ["org/team-b"]

  - name: "B: Approval from Compliance"
    if:
      has_labels: ["Label B"]
      changed_files:
        paths: ["files/b\\.yaml"]
    requires:
      count: 1
      teams: ["org/compliance"]
```

The important part is that every rule that is part of "Policy A" has the `has_labels` predicate. If the label does not exist, all of these rules are all skipped.

In a real policy, you'd probably want to add a fall back rule to handle cases where the pull request does not have either label. That might be something like:

```yaml
policy:
  approval:
    - or:
      - "Default approval"
      - and:
        # rules for policy "A"
        - "A: Approval from Team A"
        - "A: Approval from Compliance"

        # rules for policy "B"
        - "B: Approval from Team B"
        - "B: Approval from Compliance"
```
