### ISSUE TITLE
Question: How to request additional reviewers if check failed

### ISSUE THREAD

**Issue by gtirloni** [palantir/policy-bot#400]
I'm trying to express the following rule "If status check A has **failed**, require approval from team X"

```yaml
policy:
  approval:
    - "check A passed"

approval_rules:
  - name: "check passed"
    if:
      has_UNsuccessful_status:
        - "check-a"
    requires:
      count: 1
      team: ["myorg/my-team-of-extra-approvers"]
```

Would the only way to express this be to implement `has_UNsuccessful_status` or is there some other way I'm missing?

The intention is to allow certain changes to be approved if some other team is okay with overriding the policy (e.g. management might have said that they don't want changes that cost more than $X but are willing to evaluate and approve special requests).

There is also the issue of GitHub requiring all checks to pass before a merge is allowed so I'm not sure if this is the right way to implement such policy either.

Thanks in advance for any advice.

**Comment by bluekeyes** [comment]
While there's no way to set conditions based on check failures, the way I would achieve this is by using multiple rules: one that only applies when the status check is successful and one that applies in all conditions. This inverts the approach to the problem. Instead of thinking about it as adding new rules when a check fails, we remove unnecessary rules when a check is successful.

Exactly what that looks like will depend on the policy you want to enforce. Using your example of management approving expensive changes, you could do something like this:

```yaml
policy:
  approval:
    - developers approved changes in budget
    - management approved changes

approval_rules:
  - name: developers approved changes in budget
    if:
      has_successful_status:
        - "budget check"
    requires:
      count: 1
      teams: ["org/developers"]

  - name: management approved changes
    requires:
      count: 1
      teams: ["org/management"]
```

This requires management approval for expensive changes, but also assumes that management can approve all changes, regardless of how they impact the budget.

If you want to always required developer approval too, try something like this:

```yaml
policy:
  approval:
    - or:
      - developers approved changes in budget
      - and:
        - developers approved changes
        - management approved changes

approval_rules:
  - name: developers approved changes in budget
    if:
      has_successful_status:
        - "budget check"
    requires:
      count: 1
      teams: ["org/developers"]

  - name: developers approved changes
    requires:
      count: 1
      teams: ["org/developers"]

  - name: management approved changes
    requires:
      count: 1
      teams: ["org/management"]
```

In this case, if the changes are too expensive (the `budget check` status is either failed or missing), you need approval from both management and developers. Compared to the previous version, this means management cannot approve changes alone.
