### ISSUE TITLE
Support rule defaults for common options

### ISSUE THREAD

**Issue by bluekeyes** [palantir/policy-bot#41]
It would be helpful if policy-bot support a way to set default options for all rules in a policy without copying code or using YAML references. I'm imagining something like this:

```yaml
policy:
  approval:
    - rule using defaults

approval_defaults:
  options:
    invalidate_on_push: true
    ignore_update_merges: true

approval_rules:
  - name: rule using defaults
    requires:
      count: 1
      teams: ["palantir/devtools"]
```
