### ISSUE TITLE
Question around "skipped" rules

### ISSUE THREAD

**Issue by insert0** [palantir/policy-bot#411]
Hi,

I have been trying to understand what "skipped" really means in policy bot, but I couldn't get my head around it, so I am asking here hoping to get some better picture of what it means.

In the documentation, the following is mentioned.
_or, and, and if (Rule Predicates)
If the if block of a rule (the predicate) is not satisfied, the rule is marked as "skipped". Skipped rules interact with or and and as follows:

An and block containing only skipped rules is also skipped
An or block containing only skipped rules is also skipped
Effectively, skipped rules are treated as if they don't exist._

The last sentence was throwing me off. What does it mean by "skipped rules are treated as if they don't exist"? If the rule is necessary for the PR to be passed to the next step in Github workflow, any rules shouldn't be skipped or ignored. When it says "skipped", can it be considered as "false" state or it is just not considered in the decision chain?

So far, based on my analysis of the logs and behavior, if I don't specify "requires count with reviewer users", the rule gets skipped when it fails which doesn't seem to affect the final decision since the final decision was pass which should have been fail.

Please kindly advise on this as I would like to get a better understanding so I can work with the policy. The following is the policy that I have been trying to work with by adjusting here and there. The ultimate goal is to have policy bot to work with Bulldozer for seamless automerge experience for users in their Github workflow which means having "reviewers" per approval rule doesn't really make sense since it defeats the purpose of the automated pr merge process.

Thank you for your support in advance!
Best regards,
Dong-Jun

----- sample policy I use -----
```yaml
policy:
  approval:
    - and:          # <-- tried with and without this option. no difference was identified
      - author is the only contributor
      - auto approval by author
      - has valid signature          
      - build status checks
  disapproval:
    if:
      changed_files:
        paths:
          - "^(filename)$"
approval_rules:
  - name: author is the only contributor
    if:
      author_is_only_contributor: true
    options:
      request_review:
        enabled: true
        mode: all-users
      methods:
        comments:
          - "LGTM"
        comment_patterns:
          - "LGTM"
        github_review: true
        github_review_comment_patterns:
          - "LGTM"
    requires:
      count: 1
      users: ["user1"]  
  - name: auto approval by author
    if:
      has_author_in:
        users: ["user1"]
    options:
      request_review:
        enabled: true
        mode: all-users   
      methods:
        comments:
          - "LGTM"
        comment_patterns:
          - "LGTM"
        github_review: true
        github_review_comment_patterns:
          - "LGTM"        
    requires:
      count: 1
      users: ["user1"]    
  - name: build status checks
    if:
      has_successful_status:
        - "Checkout Code"        
        - "continuous-integration/jenkins/pr-merge"
        - "WhiteSource Security Check"
    options:
      request_review:
        enabled: true
        mode: all-users       
      methods:
        comments:
          - "LGTM"
        comment_patterns:
          - "LGTM"
        github_review: true
        github_review_comment_patterns:
          - "LGTM"        
    requires:
      count: 1
      users: ["user1"]    
  - name: has valid signature
    if:
      has_valid_signatures: true
      has_valid_signatures_by_keys:
        key_ids: ["xxxxxxxxxxxxx","yyyyyyyyyyyyy"]      <-- masked for security
    options:
      request_review:
        enabled: true
        mode: all-users   
      methods:
        comments:
          - "LGTM"
        comment_patterns:
          - "LGTM"
        github_review: true
        github_review_comment_patterns:
          - "LGTM"        
    requires:
      count: 1    
      users: ["user1"]    
  - name: only dockerfile
    if:
      only_changed_files:
        paths:
          - Dockerfile
    options:
      request_review:
        enabled: true
        mode: all-users 
      methods:
        comments:
          - "LGTM"
        comment_patterns:
          - "LGTM"
        github_review: true
        github_review_comment_patterns:
          - "LGTM"        
    requires:
      count: 1
      users: ["user1"]
```

**Comment by bluekeyes** [comment]
Thanks for trying out Policy Bot! To understand skipped rules, I think it helps to take a step back and look at the possible states for rules. In Policy Bot, rules only fail when there's an error, e.g. a GitHub API request fails. Instead, rules can be:

* Pending - the approval condition (the `requires` block) is not satisfied
* Successful - the approval condition (the `requires` block) is satisfied
* Skipped - the predicates (the `if` block) are not satisfied

In other words, predicates add rules to the policy when they are true and remove rules from the policy when they are false (by marking the rule as "skipped".) I like to think of policies in positive terms ("approve the pull request if these conditions are true") rather than in negative terms ("fail the pull request if these conditions are false".)

If I'm reading your policy correctly, you want pull requests to merge automatically when all of the following are true:

* The pull request is from a user in a specific list
* The author is the only contributor
* The author signed their commits
* The pull request has passing status checks

What's missing is what should happen when one of these conditions is not true. Usually, you'll fall back to some kind of manual approval in this case. Here's an example policy that might do what you want:

```yaml
policy:
  approval:
    - or:
        - Pull request is from a trusted author with signed commits
        - Admins approved

approval_rules:
  - name: Pull request is from a trusted author with signed commits
    if:
      has_author_in: ["user1"]
      author_is_only_contributor: true
      has_valid_signatures_by_keys:
        key_ids: ["xxxxx", "yyyyy"]
    requires:
      count: 0 # not necessary, but it makes the "auto-approval" behavior explicit

  - name: Admins approved
    requires:
      count: 1
      permissions: ["admin"]
```

A few things to note about this policy:

1. I read this as "A pull request is approved if it is from a trusted author with signed commits OR admins have approved". I think this makes it clear that the conditions enable a shortcut: when they are true, you don't need to get approval. But when they are false (i.e. the first rule is skipped) you must get approval from a trusted user.
2. I used a single rule for all conditions. All predicates must be true for the rule to apply.
3. I left out the status checks. I'd usually enforce this by using required status checks in GitHub branch protection. But if you want to allow a valid approval to override failing statuses, then including them here as a predicate makes sense
4. If you _really_ don't want the fallback rule that allows admin approval, you can make the condition impossible by doing something like requiring approval from a user that doesn't exist or setting `count` to a very large number.

Finally, some other tips that might help:

1. If all the rules in policy are skipped, the policy as a whole fails. After evaluation, every policy must have at least one pending or successful rule.
2. By default, rules are combined using `and`. That's why adding an explicit `and` did not change behavior
3. You should only need one of `has_valid_signatures` or `has_valid_signatures_by_keys` in any one rule

I hope this helps explain things, but please let me know if you have any other questions.
