### ISSUE TITLE
Fix UI for rules with required review by permissions

### ISSUE THREAD

**Issue by derekjobst** [palantir/policy-bot#416]
When reviews are required by permissions the UI does not display that fact:
<img width="545" alt="Screen Shot 2022-05-03 at 11 56 25 AM" src="https://user-images.githubusercontent.com/930621/166523310-6e1f198b-a8f0-4b4b-bd49-d81dea39a68f.png">

Rule:
```
  - name: one admin has approved (PR contributors not allowed)
    options:
      allow_contributor: false
    requires:
      count: 1
      permissions: ["admin", "maintain"]
```
