### ISSUE TITLE
Individual user names as in approval_rules

### ISSUE THREAD

**Issue by leslie-qiwa** [palantir/policy-bot#436]
Besides all_users, random_users, teams, is it possible to support individual user names as approval_rules. We have different branches, and each branch may only have 1 or 2 managers. Creating many teams seems overkilling for us.

**Comment by bluekeyes** [comment]
Could you provide an example policy showing what you'd like to do? I believe Policy Bot already supports what you described:

```yaml
policy:
  approval:
    - users 1 or 2 approved changes to branch A
    - users 3 or 4 approved changes to branch B

approval_rules:
  - name: users 1 or 2 approved changes to branch A
    if:
      targets_branch:
        pattern: "branch-a"
    options:
      request_review:
        enabled: true
        mode: all-users
    requires:
      count: 1
      users: ["user-1", "user-2"]

  - name: users 3 or 4 approved changes to branch B
    if:
      targets_branch:
        pattern: "branch-b"
    options:
      request_review:
        enabled: true
        mode: all-users
    requires:
      count: 1
      users: ["user-3", "user-4"]
```

In this example, if you make a pull request against `branch-a`, Policy Bot should request a review from `user-1` and `user-2`. By using the `users` key in the `requires` section, you can specify the list of users who are allowed to approve.

Note that the users must be contributors (read permission is fine, including through organization membership) for reviewer requests to work (this is not a requirement for plain approval.)
