### ISSUE TITLE
Github branch protection enforces policy bot

### ISSUE THREAD

**Issue by ekhaydarov** [palantir/policy-bot#458]
Am i missing something or is this an issue?

I have branch protection on master and develop. In the policy bot I only want to enforce it on the master branch. So naturally in my policies I use 
```
approval_rules:
  - name: approvers
    if:
      targets_branch:
        pattern: "^master$"
```

However, policy bot is still enforced on the develop branch

**Comment by bluekeyes** [comment]
Hey @ekhaydarov, it sounds like there might be some confusion about how Policy Bot works. Policy Bot does not change anything about branch protection settings in GitHub, but only posts status checks. You may choose to require these checks on som branches and not on others using GitHub's branch protection feature.

If the target branch for a pull request contains a `policy.yml` file (or there is a default policy defined using one of the methods in the docs), then Policy Bot will post a status check for the pull request.

The `targets_branch` predicate is a way to enable specific approval rules based on the target branch of the pull request. For instance, you might use this to require approvals for PRs to `master` but auto-approve PRs to any other branch:

```yaml
policy:
  approval:
    - changes to master are approved
    - all other changes are auto-approved

approval_rules:
  - name: changes to master are approved
    if:
      targets_branch:
        pattern: "^master$"
    requires:
      count: 1
      teams: ["my-org/approvers"]
  - name: all other changes are auto-approved
    requires:
      count: 0
```

In GitHub's branch protection settings, you could then require `policy-bot: master` on the `master` branch and `policy-bot: develop` on the `develop` branch.

Note that every PR must have at least one rule that applies. If the only rule in your policy has a `targets_branch` condition, then PRs to other branches will have failed status checks because all rules are skipped. As long as you don't require the check in GitHub, you could ignore these failures, or you could add a fallback rule to auto-approve like the example above.

Does that help?
