### ISSUE TITLE
Update of PR shouldn't always remove approval check

### ISSUE THREAD

**Issue by DepickereSven** [palantir/policy-bot#460]
We have the following use case:

We have non-technical people checking a certain number of files that contain files that will generate documentation.
So when they find that documentation looks fine they will approve it.

But whenever something gets pushed the bot will ask for approval again.
Would it be possible to have something as follows:

- The non-technical people approve the changes.
- Technical people make a comment, to file outside of the scope of non-technical.
- Comment gets solved
- Technical people are asked again for review while non-technical people aren't asked to review again.

If there is a change in their scope they should be asked to review the changes of course.

Does something already exist?
Or is possible to give some pointers so we can make PR for this feature?

**Comment by bluekeyes** [comment]
Most of this workflow is possible except for the final request: there is no way to selectively re-request reviews based on the files changed.

Because the `invalidate_on_push` option applies at the rule level, you can create a policy like this, where technical people have to review all changes on every push, while non-technical people only need to review once:

```
policy:
  approval:
    - docs changes are approved
    - code changes are approved

approval_rules:
  - name: docs changes are approved
    if:
      changed_files:
        paths:
          - "docs/.*"
    options:
      invalidate_on_push: false
    requires:
      count: 1
      teams: ["my-org/docs-reviewers"]
  - name: code changes are approved
    options:
      invalidate_on_push: true
    requires:
      count: 1
      teams: ["my-org/code-reviewers"]
```

This has a few disadvantages but these might be acceptable:

* Once the first rule is approved, that approval is never invalidated, even if documentation changes again
* The second rule is invalidated by any push, even if the update only touched documentation. Your technical reviewers must review all changes.

---

The main limitation for implementing this feature is that we only build modified file lists using the full pull request, rather than the changes in individual commits. If you want to try implementing this feature, I think you will need to:

1. Modify the GitHub interactions to load modified files from commits. While doing this, carefully consider how this changes the number of GitHub API requests required to evaluate a PR. You'll also need to make sure commits combine properly. For example, if a commit adds a file and a later commit removes it, the file should not influence the final evaluation.
2. Pass information about modified files back to the evaluation logic along with the existing commits
3. Modify the predicate evaluation so that you can evaluate file-based predicates on individual commits instead of only on full pull requests
4. Modify the invalidation logic to account for modified files. You will need to check if the combined modifications of all commits pushed after an approval modified any files selected by predicates of the current rule.

I think this also opens the question of if there are any other predicates that should have the same behavior. Overall, while possible, I believe this would require refactoring some of the more complicated parts of Policy Bot.
