### ISSUE TITLE
Multiple teams and requires.count > 2 produces unintuitive result

### ISSUE THREAD

**Issue by aw185176** [palantir/policy-bot#496]
A rule like

```
- name: rule/1
  if:
    changed_files:
      paths:
      - .*
  requires:
    count: 2
    teams:
    - team/1
    - team/2
```

Will require at least one review from each team. Based on the README, we were under the impression this would define a rule where 2 reviews from any combo of those teams (2 team/2, 2 team/1, 1 team/1 1 team/2) would satisfy the predicate
