### ISSUE TITLE
[Question] default reviewer for non matching rules

### ISSUE THREAD

**Issue by yongzhang** [palantir/policy-bot#587]
Hi, there

I have repo structure like this:

```
frontend
backend
folder1
folder2
.policy.yml
```

and `.policy.yml` like this:
```
policy:
  approval:
  - or
    - default
    - frontend
    - backend

approval_rules:
- name: default
  options:
    allow_contributor: true
    ignore_update_merges: true
    request_review:
      enabled: true
      mode: teams
    methods:
      github_review: true
  requires:
    count: 1
    teams: ["default"]

- name: frontend
  if:
    changed_files:
      paths:
        - "frontend/*"
  options:
    allow_contributor: true
    ignore_update_merges: true
    request_review:
      enabled: true
      mode: teams
    methods:
      github_review: true
  requires:
    count: 1
    teams: ["frontend"]

- name: backend
  if:
    changed_files:
      paths:
        - "backend/*"
  options:
    allow_contributor: true
    ignore_update_merges: true
    request_review:
      enabled: true
      mode: teams
    methods:
      github_review: true
  requires:
    count: 1
    teams: ["backend"]
```

What I expect are:

- If a PR contains changes in `frontend/*`, add team `frontend` as reviewer and require approval
- If a PR contains changes in `backend/*`, add team `backend` as reviewer and require approval
- If changed files not matching above, in my case those are `folder1, folder2 and .policy.yml`, add team `default` as reviewer and require approval

I observed the `default` reviewer was added for every PR, not sure how to write the correct rules, please help, thanks.

**Comment by bluekeyes** [comment]
This type of workflow is kind of hard to implement with Policy Bot's current features. Policy Bot will assign reviewers if three conditions are true:

1. The rule has the `request_review.enabled` property set to `true`
2. The rule evaluates to the `pending` status
3. The overall status of the policy is `pending`

The second condition is causing the problem here. Because the `default` rule has no predicates, it applies to every pull request. To get the behavior you want, you'll need to add some condition to the `default` rule. Here's one option you can try:

```yaml
- name: default
  if:
    changed_files:
      paths:
        - ".*"
      ignore:
        - "frontend/.*"
        - "backend/.*"
  options:
    allow_contributor: true
    ignore_update_merges: true
    request_review:
      enabled: true
      mode: teams
    methods:
      github_review: true
  requires:
    count: 1
    teams: ["default"]
```

This should mean that the default rule only applies when the PR changes files outside of the `frontend/` or `backend/` directories. The downside is that you have to duplicate patterns between the `default` rule and the other rules.

Also, when every rule in your policy has a predicate, be careful to make sure that at least one rule applies to every pull request: Policy Bot posts an error status when a PR skips all rules in the policy.
