### ISSUE TITLE
How to ignore a user's approval in one team when the user is member of two approval teams?

### ISSUE THREAD

**Issue by gpadavala** [palantir/policy-bot#592]
We have a bot that is in both teams, but we want its approval to be ignored w.r.t DEV team

Below is the snippet of our policy

      - name: code_review
        requires:
          count: 1
          teams:
            - DEV_TEAM
    
      - name: ops_review
        requires:
          count: 1
          teams:
            - OPS_TAM

**Comment by bluekeyes** [comment]
Unfortunately, it's not possible to ignore approvals from specific members of a team, but here are two potential workarounds:

1. Remove the bot account from both teams and add a `users` list with the bot's name to the rules where you'd like the bot to approve (you can mix `users` and `teams` conditions on the same rule.) This may not be possible if the teams are important for other purposes or you are unable to create a new team for the bot account.
2. Update the bot to leave a special comment when it approves a PR and then modify the rules where you'd like the bot to approve so that the special comment counts as approval. For example:

   ```yaml
   - name: code_review
     requires:
       count: 1
       teams:
         - DEV_TEAM
   
   - name: ops_review
     options:
       methods:
         github_review: true
         comments:
           - ":+1:"
           - "👍"
           - "==OPS_BOT_APPROVED=="
     requires:
       count: 1
       teams:
         - OPS_TEAM
   ```
   When the bot leaves comment that contains `==OPS_BOT_APPROVED==`, it will only count as an approval for the `ops_review` rule. Other users can continue to use the default comment strings or GitHub reviews.

   If you'd like the bot to use GitHub Reviews instead of comments, you can use the `github_review_comment_patterns` option to achieve a similar result.
