### ISSUE TITLE
Support diff types in file predicates

### ISSUE THREAD

**Issue by jmcampanini** [palantir/policy-bot#7]
It would be helpful to specify different approval rules for additive-only changes to certain files. This should be easy to add in code (the `File` abstraction already contains the information), so the main question is how to configure this without making the default path configuration too hard.

Maybe something like this?

```yaml
if:
  files_changed:
    paths:
      - some/path
      - some/path:
          mode: additive
```

That would be a bit annoying to parse. Maybe the mode could be specified at the top-level and applies to all paths in this predicate?

```yaml
if:
  files_changed:
    mode: additive
    paths:
      - some/path
      - some/path
```

If you want different modes on different paths, you'd have to use multiple rules, but that might actually be fine or desired for the common case (i.e. auto-approval of certain files.)
