### ISSUE TITLE
FR: Add a min_lines_of_code predicate

### ISSUE THREAD

**Issue by alexthemark** [palantir/policy-bot#70]
In my repository, I'd like to require special approval for pull requests over a certain size. E.g. if more than 1000 lines of code have been modified, a certain set of people must approve the pull request.

Would it be possible to add a predicate to support this?

**Comment by bluekeyes** [comment]
I think this a reasonable predicate request. My current design is:

```yaml
if:
  modified_lines:
    additions: "<200"
    deletions: ">400"
    total: ">1000"
```

Each expression matches the regular expression `^(<|>) ?(\d+)$`, allowing for "less than" or "greater than" comparison. All of the keys are optional, and the predicate is satisfied if any of the expressions is satisfied.

Does that work for you?
