### ISSUE TITLE
requires.conditions not working correctly in rule

### ISSUE THREAD

**Issue by reedog117** [palantir/policy-bot#785]
Have a rule that looks like this

```yaml
- name: rulename
  if:
    changed_files:
      paths:
        - path1
        - path2
  requires:
    conditions:
      has_successful_status:
        - "status check"
```

I'm getting this error when attempting to validate the policy.

```
{"message":"Policy is invalid. 'yaml: unmarshal errors:\n  line 77: field conditions not found in type common.Requires'.","version":"1.34.1"}
```

I'm guessing this isn't expected since `requires.conditions` is an example config in the README.
