### ISSUE TITLE
behavior when using `invalidate_on_push` and `ignore_commits_by`?

### ISSUE THREAD

**Issue by reedog117** [palantir/policy-bot#788]
I have the following settings in a rule in policybot.

```yaml
  - name: one approver has approved (PR contributors not allowed)
    options:
      allow_contributor: false
      invalidate_on_push: true
      ignore_commits_by:
        users: ["github-service-account"]
    requires:
      count: 1
      permissions: ["admin", "maintain"]
```

After approval, I have an automated workflow that runs some tasks and then pushes an additional commit back to the PR/branch as the `github-service-account` user. However, this invalidates the push. I thought that the commit would be ignored by policybot, but it isn't. What's the proper way to implement this?
