### ISSUE TITLE
can I have approval rule with has_author_in but in not form

### ISSUE THREAD

**Issue by MahmoudMabrok** [palantir/policy-bot#840]
Can we have something like `not_has_author_in` so rule is not needed as long as author not in list I provide. 

the case I have :
- have a admin team 
- have dev team 

if pr is by dev team, so need two approval one from dev team and one from admin team, but if author is admin , we need admin team approval only.

**Comment by bluekeyes** [comment]
Could you share an example of the policy you'd write if this predicate existed? I think it should be possible to implement what you described with existing features:

```yaml
policy:
  approval:
    - dev changes are approved by dev
    - dev changes are approved by admin
    - admin changes are approved by admin

approval_rules:
  - name: dev changes are approved by dev
    if:
      has_author_in:
        teams: ["org/dev-team"]
    requires:
      count: 1
      teams: ["org/dev-team"]

  - name: dev changes are approved by admin
    if:
      has_author_in:
        teams: ["org/dev-team"]
    requires:
      count: 1
      teams: ["org/admin-team"]

  - name: admin changes are approved by admin
    if:
      has_author_in:
        teams: ["org/admin-team"]
    requires:
      count: 1
      teams: ["org/admin-team"]
```
