### ISSUE TITLE
How we can exclude bot from approval

### ISSUE THREAD

**Issue by rajesh-dhakad** [palantir/policy-bot#847]
We have a usecase where the `gh-auto-approve` bot approves the PR - how can I exclude `gh-auto-approve` from approval_rules? 

Note: `gh-auto-approve` is part of our `org/eng` team which we want to keep as it is.

```
policy:
  approval:
        - the eng team approval

approval_rules:
  - name: the eng team approval
    requires:
      count: 1
      teams:
        - "org/eng"
```
