### ISSUE TITLE
Support glob filename patterns

### ISSUE THREAD

**Issue by reegnz** [palantir/policy-bot#853]
When working with files, policy-bot should be providing basic glob support.

When working with common unix tools, glob-support tends to be either built-in, or augmented by the wrapping shell evaluating globs. It's not that common using regex to match filename patterns.

Using filename pattern matching is arguable also more secure than raw regex.

Please support either globs or gitignore patterns (which also resemble globs).

Seems like go has glob functionality already built into it's standard library, and is much more performant in matching filenames than regex:
https://github.com/golang/go/blob/master/src/path/filepath/match.go#L44

I imagine config could look like this:

```
changed_files:
  glob: true
  paths:
  - **/*.yaml
  - **/some/**/pattern/*.py
  
```
