### ISSUE TITLE
File-based policies fail when file is removed

### ISSUE THREAD

**Issue by iainlane** [palantir/policy-bot#854]
Perhaps this is a duplicate of #246 - no problem closing if so.

This is one of our rules:

```yaml
  - name: Workflow .github/workflows/linters.yml succeeded or skipped
    requires:
      conditions:
        has_workflow_result:
          conclusions:
            - skipped
            - success
          workflows:
            - .github/workflows/linters.yml
```

If we ever delete or rename `.github/workflows/linters.yml`, the policy won't pass and the PR will not be able to be merged.

I'm wondering about a `file_exists` predicate, or perhaps supporting `{ADDED, CHANGED, MODIFIED, REMOVED}` on `changed_files` and `no_changed_files`. So it'd look something like:

```yaml
  - name: Workflow .github/workflows/linters.yml succeeded or skipped
    if:
      no_changed_files:
        paths:
          - path: .github/workflows/linter.yml
            types: [REMOVED]
    requires:
      conditions:
        has_workflow_result:
          conclusions:
            - skipped
            - success
          workflows:
            - .github/workflows/linters.yml
```

or

```yaml
  - name: Workflow .github/workflows/linters.yml succeeded or skipped
    if:
      file_exists:
        - github/workflows/linter.yml
    requires:
      conditions:
        has_workflow_result:
          conclusions:
            - skipped
            - success
          workflows:
            - .github/workflows/linters.yml
```
