### ISSUE TITLE
author_is_only_contributor does not work with file edits from Github UI

### ISSUE THREAD

**Issue by dsw2127** [palantir/policy-bot#88]
If you edit a file in the Github UI directly and create a PR from there, the `author_is_only_contributor` condition does not hold.

For example I made the following policy on a test project:
```
policy:
  approval:
    - dwalker is author

approval_rules:
  - name: dwalker is author
    if:
      author_is_only_contributor: true
      has_author_in:
        users: ["dwalker"]
    options:
      invalidate_on_push: true
    requires:
      count: 0
```
and then created a test PR. The "dwalker is author" rule was skipped and had the message "Commit 5d0b04b219 was authored or committed by a different user". Looking at the commit you can see indeed Github is listed as the committer, not me:

```
$ git show --pretty=fuller 5d0b04b219
commit 5d0b04b2197e4442616269a24eb9efa092a682e9 (origin/dwalker-patch-1)
Author:     Dan Walker <redacted>
AuthorDate: Thu Jun 6 15:53:27 2019 -0400
Commit:     GitHub Enterprise <noreply@redacted>
CommitDate: Thu Jun 6 15:53:27 2019 -0400

    Create test
```

Is there a way to make this still work?
