### ISSUE TITLE
review dismissal question

### ISSUE THREAD

**Issue by devinburnette** [palantir/policy-bot#893]
Hello,

I think I'm currently hitting an edge case introduced in: https://github.com/palantir/policy-bot/pull/577

As described in the bottom of that PR description:

> If a single approval satisfies rules A and B where A is invalidated by pushes and B is not, pushing a new commit will not dismiss the review (because it still satisfies B). This is the intended behavior, but it could confuse people. I think in practice conflicting rules like this are behind predicates.

Most of our rules are "reviews with comments" type of policies where the github review could potentially contain a comment satisfying multiple policy rules. So it is a bit surprising to us to see that a new commit being pushed post approval makes the policy go back to pending after the re-evaluation, but doesn't actually dismiss the github review. This is where in the original implementation, I was thinking the "reason" field could clearly state which candidate is the cause of the review being dismissed. 

Example policy:
```
policy:
  approval:
      - and:
          - domain review
          - platform review

approval_rules:
- name: domain review
  requires:
    count: 1
    teams:
    - "some-org/engineering"
  options:
    ignore_edited_comments: true
    invalidate_on_push: true
    allow_non_author_contributor: true
    methods:
      comments: []
      github_review: true
      github_review_comment_patterns:
        - '(?i)\bdomain\s*lgtm\b'
- name: platform review
  requires:
    count: 1
    teams:
    - "some-org/platform-reviewers"
  options:
    ignore_edited_comments: true
    invalidate_on_push: false
    allow_non_author_contributor: true
    methods:
      comments: []
      github_review: true
      github_review_comment_patterns:
        - '(?i)\bplatform\s*lgtm\b'
```

Is there a way to have it still dismiss the github review commenting the reason with this set up? You mention using predicates, is there a way to refactor this policy to accomplish what we want with predicates?
