### ISSUE TITLE
[Question]: Is it possible to add multiple policy based on branches?

### ISSUE THREAD

**Issue by satizzzzz** [palantir/policy-bot#943]
Hi,

Is it possible to add multiple policy based on branches?

I have 2 branches, main and develop, on raising PR from feature/* against it should perform some validation and on another PR raised from develop against main, there are different validation.

Basically it should check the approval_rules based on target_branch. is it possible?

**Comment by bluekeyes** [comment]
Policy Bot reads the policy file from the target branch of a pull request. If you have two completely independent branches, you can add a different policy to each branch. Unfortunately, this doesn't work as well if you regularly merge one branch in to the other.

The other option is the `targets_branch` predicate. This applies at the rule level, not at the level of the full policy, but allows you to enable or disable rules based on the target branch. For example:

```yaml
policy:
  approval:
    # rules for main
    - changes to main are approved by release managers
    # rules for develop
    - changes to develop are approved by engineering

approval_rules:
  - name: changes to main are approved by release managers
    if:
      targets_branch:
        pattern: "^main$"
    requires:
      count: 1
      teams: ["my-org/release-managers"]

  - name: changes to develop are approved by engineering
    if:
      targets_branch:
        pattern: "^develop$"
    requires:
      count: 1
      teams: ["my-org/devs"]
```

You can also have common rules that apply to all branches. When a pull requests targets a branch that does not match the `targets_branch` pattern, the rule enters the "skipped" state and is effectively ignored by the policy.

**Comment by satizzzzz** [comment]
Thanks @bluekeyes 

I have below policy, so you're saying if conditions are not satisfied it will show as skipped. 

```
policy:
  approval:
    - or:
      - main rule
      # - develop rule
approval_rules:
  - name: main rule
    if:
      from_branch:
        pattern: "^hotfix/.*$"
      targets_branch:
        pattern: "^main$"
      only_changed_files:
        paths:
          - "^backend/.*$"
          - "^frontend/.*$"
```
          
Is there any way to inform PR creator that due to some specific reason this has been skipped.  Also i want to ignore all other files changes except backend and frontend folders

<img width="843" alt="Image" src="https://github.com/user-attachments/assets/1e215ab6-410f-4a39-956e-d988a171dcca" />
