### ISSUE TITLE
Exclude other files which are not mentioned in the

### ISSUE THREAD

**Issue by satizzzzz** [palantir/policy-bot#951]
Hi, I have below policy with changed files path & ignore. Here i have defined every folders in the repo except backend and frontend  folder changes. In future, there may any new files/folders will be added.

Is there any options to have some wildcard(or anything else) exclude everything except the ones which mentioned in the paths?

```
policy:
  approval:
    - or:
      - main rule 1
      
approval_rules:
  - name: main rule 1
    if:
      from_branch:
        pattern: "^hotfix/.*$"
      targets_branch:
        pattern: "^main$"
      changed_files:
        paths:
          - "^backend/.*$"
          - "^frontend/.*$"
        ignore:
          - "^.github/.*$"
          - "^config/special\\.file$"
          - "^argocd/.*$"
          - "^plat-eng/.*$"
          - "^docs/.*$"
          - "^scripts/.*$"
          - "^solutions/.*$"
          - "^terraform/.*$"
```
