### ISSUE TITLE
policy-bot is being stuck on GH step check condition

### ISSUE THREAD

**Issue by rajesh-dhakad** [palantir/policy-bot#959]
We started seeing cases where the policy-bot is stuck indefinitely on GH step status. 

![Image](https://github.com/user-attachments/assets/fb41c389-c796-4bdc-99cb-4b3400ba58c5)

**GH step status completed before the approval ( difference of 4 minutes )  but in above screen shot it still show as 0/1 required conditions:**
<img width="822" alt="Image" src="https://github.com/user-attachments/assets/a6f8cb08-bafc-4b8a-9b75-5e365a610f76" />

**policy truncated non required portion:** 
```
# the high level policy
policy:
  approval:
    - and:
      - or:
          - db-migration squad approved or self-review passed
          - and:
            - non-migration files exists - db-migration squad approved or self-review passed
            - non-migration files exists - addition review from respective squad

# the list of rules
approval_rules:
  - name: db-migration squad approved or self-review passed
    if:
      changed_files:
        paths:
          - "^db-migration-files/.*$"
    requires:
      count: 1
      teams:
        - "org/db-migrations"
      conditions:
        has_status:
          conclusions: [ "failure", "success" ]
          statuses:
            - "review-migration-pr"
  - name: non-migration files exists - db-migration squad approved or self-review passed
    if:
      changed_files:
        paths:
          - "^db-migration-files/.*$"
    requires:
      count: 1
      teams:
        - "org/db-migrations"
      conditions:
        has_status:
          conclusions: [ "failure", "success" ]
          statuses:
            - "review-non-migration-pr"
  - name: non-migration files exists - addition review from respective squad
    if:
      changed_files:
        paths:
          - "^db-migration-files/.*$"
    requires:
      count: 2
      teams:
        - "org/eng"
      conditions:
        has_status:
          conclusions: [ "failure","success" ]
          statuses:
            - "review-non-migration-pr"
```
